server:
  port: 8080
spring:
  application:
    name: journey-lab-rest-countries
  cloud:
    openfeign:
      client:
        config:
          countryClient:
            url: ${COUNTRY_API_URL}
          default:
            connectTimeout: 3000
            readTimeout: 5000
logging:
  level:
    feign: DEBUG
    dev.journey.restcountries.client: DEBUG