name: CI and Auto PR to Develop

on:
  push:
    branches:
      - 'feature/**'
      - 'fix/**'

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean install

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Run Tests
        run: mvn test

  open-pull-request:
    name: Open PR to Develop
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install GitHub CLI
        run: sudo apt-get install gh -y
      - name: Authenticate CLI
        run: gh auth login --with-token <<< "${{ secrets.GH_TOKEN }}"
      - name: Create Pull Request
        run: |
          sed -i "s#\${{ github.ref_name }}#${GITHUB_REF_NAME}#g" .github/pr-body.md
          gh pr create \
            --base develop \
            --head ${{ github.ref_name }} \
            --title "Auto PR from ${{ github.ref_name }}" \
            --body-file .github/pr-body.md || echo "PR já existente ou sem alterações."
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_REF_NAME: ${{ github.ref_name }}