name: Open PR from develop to main

on:
  push:
    branches:
      - develop

permissions:
  contents: write
  pull-requests: write

jobs:
  pr-develop-main:
    name: Open PR to Main
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate GitHub CLI
        run: gh auth login --with-token <<< "${{ secrets.GH_TOKEN }}"

      - name: Create Pull Request from develop to main
        run: |
          gh pr create \
            --base main \
            --head develop \
            --title "Auto PR from develop to main" \
            --body-file .github/pr-body-develop-to-main.md || echo "PR já existente ou sem alterações."

        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
